# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

name: Update data

on:
  schedule:
    - cron: "0 6 * * 5"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip
          cache-dependency-path: requirements.txt
      - run: pip install -r requirements.txt
      - name: Create env file
        run: |
          echo "${{ secrets.ENV_FILE }}" > api_config.env
      - name: Update data
        run: |
          ./weekly_report.sh
      - name: git config
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: git commit and push any changes
        run: |
          git add .
          git diff-index --quiet HEAD || (git commit -m "Update data" && git push)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Update Google sheet
        run: |
          python scripts/export_to_sheets.py
